# Dockerfile for Tests
FROM python:3.10

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory
WORKDIR /tests

# Copy the requirements file
COPY Pipfile Pipfile.lock ./

# Install pipenv
RUN pip install --no-cache-dir pipenv

# Install the dependencies
RUN pipenv install --system --deploy

# Copy the application files
COPY tests ./tests

# Set the PYTHONPATH environment variable
ENV PYTHONPATH=/tests

# Expose the port the app runs on
EXPOSE 8000

# Command to keep alive
ENTRYPOINT ["tail", "-f", "/dev/null"]
